//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvanceUMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClearance
    {
        public System.Guid? uqClearanceCode { get; set; }
        public Nullable<System.Guid> uqWorkerCode { get; set; }
        public string strEngineeerRemarks { get; set; }
        public Nullable<System.DateTime> dtEngineerRemarks { get; set; }
        public string strClearanceRemarks { get; set; }
        public Nullable<System.DateTime> dtClearanceRemarks { get; set; }
        public string strContractotRemarks { get; set; }
        public Nullable<System.DateTime> dtContractorRemarks { get; set; }
        public string strFeedback { get; set; }
        public Nullable<System.DateTime> dtCreatedAt { get; set; }
        public Nullable<System.DateTime> dtMoidifyAt { get; set; }
        public Nullable<System.Guid> uqCreatedBy { get; set; }
        public Nullable<System.Guid> uqModifyBy { get; set; }
        public string Year { get; set; }
    }
}
