//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvanceUMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSetting
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string LogoPath { get; set; }
        public string FeviconPath { get; set; }
        public string SMTPHost { get; set; }
        public string SMTPUserName { get; set; }
        public string SMTPPassword { get; set; }
        public string SMTPEmail { get; set; }
        public string SMTPPort { get; set; }
    }
}
