//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvanceUMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTAPlanning
    {
        public System.Guid? intTAPlanningCode { get; set; }
        public Nullable<System.Guid> uqTradeCode { get; set; }
        public string strTradeName { get; set; }
        public Nullable<System.Guid> uqShiftCode { get; set; }
        public string strShiftName { get; set; }
        public Nullable<System.Guid> uqAreaCode { get; set; }
        public string strAreaName { get; set; }
        public Nullable<System.Guid> uqDepartmentCode { get; set; }
        public string strDepartmentName { get; set; }
        public System.DateTime dtFrom { get; set; }
        public Nullable<System.DateTime> dtTo { get; set; }
        public Nullable<int> intDays { get; set; }
        public System.DateTime dtCreatedAt { get; set; }
        public Nullable<System.DateTime> dtMoidifyAt { get; set; }
        public System.Guid uqCreatedBy { get; set; }
        public Nullable<System.Guid> uqModifyBy { get; set; }
        public string Year { get; set; }
    }
}
