//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvanceUMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.tblToDoes = new HashSet<tblToDo>();
            this.tblUserLogs = new HashSet<tblUserLog>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> RoleID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string Gender { get; set; }
        public string PhotoPath { get; set; }
        public string FacebookLink { get; set; }
        public string TwitterLink { get; set; }
        public string GoogleLink { get; set; }
        public string LinkedInLink { get; set; }
        public string SkypeID { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> IsSupervisor { get; set; }
        public Nullable<System.Guid> uqSupervisorCode { get; set; }
        public Nullable<bool> IsEngineer { get; set; }
        public Nullable<System.Guid> uqEngineerCode { get; set; }
        public Nullable<bool> IsHOD { get; set; }
        public Nullable<System.Guid> uqHODCode { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<bool> IsLockedOut { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> LastLockoutDate { get; set; }
        public Nullable<int> FailedPasswordCount { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public Nullable<System.Guid> InsertBy { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
        public Nullable<System.Guid> uqContractorCode { get; set; }
    
        public virtual tblContractor tblContractor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblToDo> tblToDoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserLog> tblUserLogs { get; set; }
    }
}
