//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdvanceUMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorker
    {
        public System.Guid? uqId { get; set; }
        public Nullable<System.Guid> uqContractorUserId { get; set; }
        public string strName { get; set; }
        public string strNextOfKin { get; set; }
        public string strNextOfKinContactNo { get; set; }
        public string strFatherName { get; set; }
        public string strCNIC { get; set; }
        public string strContact { get; set; }
        public string strEmergencyNo { get; set; }
        public Nullable<int> intAge { get; set; }
        public string strWorkderId { get; set; }
        public Nullable<System.DateTime> dtSafety { get; set; }
        public Nullable<bool> bolIsClearance { get; set; }
        public string strAddress { get; set; }
        public Nullable<System.Guid> uqTradeCode { get; set; }
        public string strQualification { get; set; }
        public Nullable<System.Guid> uqSkillCode { get; set; }
        public string uqExperienceCode { get; set; }
        public string strTAattended { get; set; }
        public Nullable<System.DateTime> dtLastTAyear { get; set; }
        public Nullable<decimal> intTARate { get; set; }
        public Nullable<System.Guid> uqSupervisorCode { get; set; }
        public Nullable<System.Guid> uqAreaCode { get; set; }
        public Nullable<System.DateTime> dtDurationFrom { get; set; }
        public Nullable<System.DateTime> dtDurationTo { get; set; }
        public Nullable<System.Guid> uqResidenceCode { get; set; }
        public Nullable<System.Guid> uqContractorCode { get; set; }
        public Nullable<System.Guid> uqDepartmentCode { get; set; }
        public Nullable<System.Guid> uqAccommodationCode { get; set; }
        public Nullable<System.Guid> uqRelationshipCode { get; set; }
        public Nullable<System.Guid> uqShiftCode { get; set; }
        public Nullable<System.DateTime> dtTAyear { get; set; }
        public byte[] vbrPicture { get; set; }
        public byte[] vbrPicture1 { get; set; }
        public Nullable<System.Guid> intJoiningStatusCode { get; set; }
        public Nullable<System.DateTime> dtLastCheckedIn { get; set; }
        public Nullable<int> intTACurrentRate { get; set; }
        public Nullable<int> intDehireStatus { get; set; }
        public Nullable<System.DateTime> dtDehire { get; set; }
        public Nullable<bool> bolIsSafetyVerified { get; set; }
        public Nullable<bool> bolIsWorkerApproveByEng { get; set; }
        public Nullable<System.DateTime> dtCreatedAt { get; set; }
        public Nullable<System.DateTime> dtMoidifyAt { get; set; }
        public Nullable<System.Guid> uqCreatedBy { get; set; }
        public Nullable<System.Guid> uqModifyBy { get; set; }
        public string Year { get; set; }
    }
}
